# Generated by Django 2.2 on 2019-05-02 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20190502_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departaments',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Units', verbose_name='Структура'),
        ),
    ]
