# Generated by Django 2.2 on 2019-05-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_departament_block_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament_block',
            name='slug',
        ),
    ]
